name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the docker image
        run: docker build -t proxz-build build

      - name: Run the docker image
        run: docker run --rm -v ${{ github.workspace }}/src:/go/src/proxz proxz-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxz
          path: ./src/proxz
